### ISSUE TITLE
waypoint visualizer does not run in hydro

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/autonomous_patrolling#119]
I getr an error when I try to visualize the waypoints onhydro

**Comment by cburbridge** [comment]
what error?

**Comment by bfalacerda** [comment]
before it was a problem with adding new markers, i think due to the use of hydro's version of interactive_markers. However, now it has the reading from database problem that the patroller has:

```
Traceback (most recent call last):
  File "/home/strands/devel_ws/src/autonomous_patrolling/waypoint_visualiser/scripts/visualise.py", line 184, in <module>
    visualiser = Visualiser()
  File "/home/strands/devel_ws/src/autonomous_patrolling/waypoint_visualiser/scripts/visualise.py", line 82, in __init__
    meta, p = ros_datacentre.util.document_to_msg(entry, TYPE=Pose)
  File "/home/strands/devel_ws/src/ros_datacentre/ros_datacentre/src/ros_datacentre/util.py", line 72, in document_to_msg
    _fill_msg(msg,document)
  File "/home/strands/devel_ws/src/ros_datacentre/ros_datacentre/src/ros_datacentre/util.py", line 53, in _fill_msg
    _fill_msg(getattr(msg,i),dic[i])
AttributeError: 'Pose' object has no attribute 'msg'
```

**Comment by hawesie** [comment]
Ah, this is the same problem that the patroller had then. You can probably copy the code from patroller.py (see [line 94 onwards](https://github.com/strands-project/autonomous_patrolling/blob/hydro-devel/waypoint_patroller/src/waypoint_patroller/patroller.py#L94)) to get this working again.
