### ISSUE TITLE
Patroller crashes after update

### ISSUE THREAD

**Issue by ghost** [strands-project/autonomous_patrolling#74]
I just started the patroller and I got the following error:

```
process[patroller-4]: started with pid [8585]
[INFO] [WallTime: 1383930075.139139] Executing waypoint_patroller with sequential point selection.
[INFO] [WallTime: 1383930075.139434] Executing waypoint_patroller with infinite iterations
[INFO] [WallTime: 1383930075.142802] Fri Nov  8 18:01:15 [initandlisten] connection accepted from 127.0.0.1:55163 #25
[INFO] [WallTime: 1383930075.144051] Fri Nov  8 18:01:15 [conn25] end connection 127.0.0.1:55163
[INFO] [WallTime: 1383930075.262553] Fri Nov  8 18:01:15 [initandlisten] connection accepted from 127.0.0.1:55229 #26
[ERROR] [WallTime: 1383930075.264750] Passing on logger to _dock_undock
[ERROR] [WallTime: 1383930075.265911] Passing on logger to _bump_monitored_dk_undk
[ERROR] [WallTime: 1383930075.266450] Passing on logger to _bumper_monitor
[ERROR] [WallTime: 1383930075.266796] Passing on logger to _dock_undock_bahaviour
[ERROR] [WallTime: 1383930075.267148] Passing on logger to _dock_to_charge
[ERROR] [WallTime: 1383930075.267433] Passing on logger to _undock_from_charge
[ERROR] [WallTime: 1383930075.267700] Passing on logger to _nav_pause_monitor
[ERROR] [WallTime: 1383930075.267994] Passing on logger to _nav_resume_monitor
[ERROR] [WallTime: 1383930075.269614] Passing on logger to _recover_bumper
[ERROR] [WallTime: 1383930075.270981] Passing on logger to _high_level_move_base_charge
[ERROR] [WallTime: 1383930075.272173] Passing on logger to _monitored_recoverable_move_base
[ERROR] [WallTime: 1383930075.272497] Passing on logger to _bumper_monitor
[ERROR] [WallTime: 1383930075.272858] Passing on logger to _carpet_monitor
[ERROR] [WallTime: 1383930075.275864] Passing on logger to _nav_pause_monitor
[ERROR] [WallTime: 1383930075.276715] Passing on logger to _recoverable_move_base
[ERROR] [WallTime: 1383930075.277062] Passing on logger to _move_base_action
[ERROR] [WallTime: 1383930075.277421] Passing on logger to _recover_move_base
[ERROR] [WallTime: 1383930075.277683] Passing on logger to _nav_resume_monitor
[ERROR] [WallTime: 1383930075.277917] Passing on logger to _recover_bumper
[ERROR] [WallTime: 1383930075.278179] Passing on logger to _recover_carpet
[ERROR] [WallTime: 1383930075.278419] Passing on logger to _high_level_move_base_patrol
[ERROR] [WallTime: 1383930075.278646] Passing on logger to _monitored_recoverable_move_base
[ERROR] [WallTime: 1383930075.278955] Passing on logger to _bumper_monitor
[ERROR] [WallTime: 1383930075.279172] Passing on logger to _carpet_monitor
[ERROR] [WallTime: 1383930075.279433] Passing on logger to _nav_pause_monitor
[ERROR] [WallTime: 1383930075.279728] Passing on logger to _recoverable_move_base
[ERROR] [WallTime: 1383930075.279976] Passing on logger to _move_base_action
[ERROR] [WallTime: 1383930075.280240] Passing on logger to _recover_move_base
[ERROR] [WallTime: 1383930075.280486] Passing on logger to _nav_resume_monitor
[ERROR] [WallTime: 1383930075.280694] Passing on logger to _recover_bumper
[ERROR] [WallTime: 1383930075.280928] Passing on logger to _recover_carpet
[ERROR] [WallTime: 1383930075.281176] Passing on logger to _point_chooser
[ERROR] [WallTime: 1383930075.281420] Passing on logger to _very_low_battery
[INFO] [WallTime: 1383930075.295987] Updating patroller thresholds::
[INFO] [WallTime: 1383930075.296303] V.Low=20
[INFO] [WallTime: 1383930075.296514] Low=35
[INFO] [WallTime: 1383930075.296723] Charged=98
[INFO] [WallTime: 1383930075.296936] Max bumper recovers before sending e-mail=10
[INFO] [WallTime: 1383930075.297141] Max move_base recovers before going to a new point=5
[INFO] [WallTime: 1383930075.334517] State machine starting in initial state 'POINT_CHOOSER' with userdata:
        []
[ERROR] [WallTime: 1383930076.336233] InvalidUserCodeError: Could not execute state 'POINT_CHOOSER' of type '<waypoint_patroller.patroller.PointChooser object at 0x2c0efd0>': Traceback (most recent call last):
  File "/opt/strands/strands_catkin_ws/src/catkinized_smach/smach/src/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/patroller.py", line 126, in execute
    current_pt = self.points[self.current_point]
IndexError: list index out of range

Traceback (most recent call last):
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py", line 118, in <module>
    l.main()
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py", line 63, in main
    outcome = self.long_term_patrol_sm.execute()
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/patroller.py", line 226, in execute
    outcome = smach.StateMachine.execute(self)
  File "/opt/strands/strands_catkin_ws/src/catkinized_smach/smach/src/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/strands/strands_catkin_ws/src/catkinized_smach/smach/src/smach/state_machine.py", line 246, in _update_once
    raise smach.InvalidUserCodeError("Could not execute state '%s' of type '%s': " % ( self._current_label, self._current_state ) + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x2c6e3b0>
 started in 5.597 s
```

Considering the patroller hasn't been updated in the past few days, I am wondering if this is based on a change in the datacenter?

**Comment by RaresAmbrus** [comment]
I remember getting this at some point and I think it's because you started the patroller with the wrong waypoint list name. You should double check that you used the same name as the one used for the list of waypoints uploaded in the database.

**Comment by cburbridge** [comment]
I think that most likely reason for this error is that the waypoints are not in your datacentre. The above bug fixes will give a more user friendly output if this is the case, so please try running this new version and see what the output is.

**Comment by lucasb-eyer** [comment]
Thank you @cburbridge, but your code didn't trigger. The root of the problem was a misnaming of the waypointset. [This error](https://github.com/cburbridge/autonomous_patrolling/blob/master/waypoint_patroller/src/waypoint_patroller/patroller.py#L68) triggered, but since it doesn't abort the node (why doesn't it raise an exception?), there were many follow-up errors and the original error message got buried.

**Comment by cburbridge** [comment]
@lucasb-eyer Oops. Above commit adds that missing exception.
