### ISSUE TITLE
KeyError: 'BUMPER_MONITOR'

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#92]
Error spotted in @AlexanderHermans report here: https://github.com/strands-project/scitos_robot/issues/32#issuecomment-28874842

```
[ERROR] [WallTime: 1384915862.954833] InvalidUserCodeError: Could not execute child termination callback: Traceback (most recent call last):
  File "/opt/strands/strands_catkin_ws/src/catkinized_smach/smach/src/smach/concurrence.py", line 348, in _state_runner
    preempt_others = self._child_termination_cb(self._child_outcomes)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/navigation.py", line 157, in child_term_cb
    if ( outcome_map['BUMPER_MONITOR'] == 'invalid' or
KeyError: 'BUMPER_MONITOR'

Exception in thread concurrent_split:BATTERY_MONITOR:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/strands/strands_catkin_ws/src/catkinized_smach/smach/src/smach/concurrence.py", line 350, in _state_runner
    raise smach.InvalidUserCodeError("Could not execute child termination callback: "+traceback.format_exc())
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x3af46c8>
```

**Comment by bfalacerda** [comment]
That's a SMACH bug, where a child of a concurrence container terminates before its parent. Then, when the concurrence container looks  for that child and does not find it, this error is printed. However, the state machine continues executing normally, I never saw anything freezing because of this. You can see that in this case the state machine continued executing normally afterwards.

**Comment by hawesie** [comment]
OK, cool. Has this bug been reported upstream?

**Comment by bfalacerda** [comment]
No. I'll do it

**Comment by hawesie** [comment]
Cool, thanks.
